## node configurations
node:
  ## the mode of node: authority/storage/watcher
  mode: "storage"
  externalIp: ""
  domainName: ""
  chainWsUrl: "ws://127.0.0.1:9944"
  profile: testnet
  backupChainWsUrls:
    - wss://testnet-rpc0.cess.cloud/ws/
    - wss://testnet-rpc1.cess.cloud/ws/
## chain configurations
chain:
  ## the name of chain node
  name: "cess"
  ## the port of chain node
  port: 30336
## bucket configurations
bucket:
  port: 15001
  space: 300
  incomeAccount: "cXgnshN4wJnCQo8fSRJDzZJS4JuGBeGNzSegW38dz8eecT5Gf"
  signPhrase: "simple vicious amazing monster nurse dance memory unknown piece fine aware flight"
  diskPath: "/cess"
  bootAddr: _dnsaddr.boot-kldr-testnet.cess.cloud
## kaleido configurations
kaleido:
  agentPort: 10010
  kaleidoPort: 4001
  bootPeerIds: ""
  stashAccount: ""
  controllerPhrase: ""
